# Generated by Django 3.2.17 on 2023-02-01 21:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Review',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='review',
        ),
    ]
